-- Pulsesend notification schema (PostgreSQL 16)
-- Applied on every boot; every statement is idempotent.

CREATE TABLE IF NOT EXISTS notification_templates (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(80)   NOT NULL UNIQUE,
    channel          VARCHAR(16)   NOT NULL,
    subject_template VARCHAR(200)  NOT NULL,
    body_template    VARCHAR(2000) NOT NULL,
    active           BOOLEAN       NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS notification_preferences (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_ref VARCHAR(120) NOT NULL,
    channel       VARCHAR(16)  NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    updated_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_preferences_recipient_channel UNIQUE (recipient_ref, channel)
);

CREATE TABLE IF NOT EXISTS notifications (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_ref VARCHAR(40)   NOT NULL UNIQUE,
    recipient_ref    VARCHAR(120)  NOT NULL,
    destination      VARCHAR(160)  NOT NULL,
    channel          VARCHAR(16)   NOT NULL,
    template_code    VARCHAR(80)   NOT NULL,
    payload          VARCHAR(2000) NOT NULL DEFAULT '{}',
    status           VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    attempts         INT           NOT NULL DEFAULT 0,
    last_error       VARCHAR(300),
    created_at       TIMESTAMPTZ   NOT NULL,
    updated_at       TIMESTAMPTZ   NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON notifications (recipient_ref);
CREATE INDEX IF NOT EXISTS idx_notifications_status ON notifications (status);

CREATE TABLE IF NOT EXISTS delivery_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT      NOT NULL REFERENCES notifications (id),
    attempt_no      INT         NOT NULL,
    outcome         VARCHAR(20) NOT NULL,
    detail          VARCHAR(300),
    created_at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_delivery_log_notification ON delivery_log (notification_id);

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(160) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role_name     VARCHAR(40)  NOT NULL
);
