-- Vantage Supply inventory schema (PostgreSQL 16)
-- Applied on every boot; every statement is idempotent.

CREATE TABLE IF NOT EXISTS warehouses (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code   VARCHAR(12) NOT NULL UNIQUE,
    name   VARCHAR(80) NOT NULL,
    city   VARCHAR(80) NOT NULL,
    active BOOLEAN     NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS products (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku           VARCHAR(32)  NOT NULL UNIQUE,
    name          VARCHAR(160) NOT NULL,
    unit          VARCHAR(16)  NOT NULL DEFAULT 'EACH',
    reorder_level INT          NOT NULL DEFAULT 0,
    active        BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS suppliers (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  VARCHAR(12)  NOT NULL UNIQUE,
    name  VARCHAR(120) NOT NULL,
    email VARCHAR(160) NOT NULL
);

CREATE TABLE IF NOT EXISTS stock_levels (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id         BIGINT      NOT NULL REFERENCES products (id),
    warehouse_id       BIGINT      NOT NULL REFERENCES warehouses (id),
    quantity_on_hand   INT         NOT NULL DEFAULT 0,
    quantity_reserved  INT         NOT NULL DEFAULT 0,
    updated_at         TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_stock_levels_product_warehouse UNIQUE (product_id, warehouse_id)
);

CREATE TABLE IF NOT EXISTS stock_movements (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference     VARCHAR(32)  NOT NULL,
    product_id    BIGINT       NOT NULL REFERENCES products (id),
    warehouse_id  BIGINT       NOT NULL REFERENCES warehouses (id),
    movement_type VARCHAR(20)  NOT NULL,
    quantity      INT          NOT NULL,
    reason        VARCHAR(200),
    created_at    TIMESTAMPTZ  NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_movements_product_warehouse ON stock_movements (product_id, warehouse_id, created_at DESC);

CREATE TABLE IF NOT EXISTS purchase_orders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_number     VARCHAR(24) NOT NULL UNIQUE,
    supplier_id   BIGINT      NOT NULL REFERENCES suppliers (id),
    warehouse_id  BIGINT      NOT NULL REFERENCES warehouses (id),
    status        VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    expected_date DATE        NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS purchase_order_lines (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id  BIGINT         NOT NULL REFERENCES purchase_orders (id),
    product_id         BIGINT         NOT NULL REFERENCES products (id),
    quantity_ordered   INT            NOT NULL,
    quantity_received  INT            NOT NULL DEFAULT 0,
    unit_cost          NUMERIC(12, 2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_po_lines_order ON purchase_order_lines (purchase_order_id);

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(160) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role_name     VARCHAR(40)  NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE
);
