spring:
  datasource:
    url: jdbc:h2:mem:banktest;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  sql:
    init:
      mode: never

banking:
  transfer:
    daily-limit: 50000.00
    reference-prefix: TRF
  account:
    number-prefix: MB
    minimum-opening-balance: 0.00

logging:
  level:
    org.hibernate.SQL: WARN
    com.meridian.banking: INFO
